language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t ghislop/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ghislop/react-test npm test

after_success:
    - docker build -t ghislop4/multi-client ./client
    - docker build -t ghislop4/multi-nginx ./nginx
    - docker build -t ghislop4/multi-server ./server
    - docker build -t ghislop4/multi-worker ./worker
    # log in to cocker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push to docker hub
    - docker push multi-client
    - docker push multi-nginx
    - docker push multi-server
    - docker push multi-worker