sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ghislop4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ghislop4/react-test npm test -- --coverage

after_success:
  - docker build -t ghislop4/multi-client ./client
  - docker build -t ghislop4/multi-nginx ./nginx
  - docker build -t ghislop4/multi-server ./Server
  - docker build -t ghislop4/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ghislop4/multi-client
  - docker push ghislop4/multi-nginx
  - docker push ghislop4/multi-server
  - docker push ghislop4/multi-worker
